# Generated by Django 5.0.6 on 2025-01-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('bill_number', models.CharField(default='No Bill', max_length=20)),
                ('other', models.CharField(blank=True, default=' ', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('particulars', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('bill_number', models.CharField(default='No Bill', max_length=20)),
                ('other', models.CharField(blank=True, default=' ', max_length=255, null=True)),
            ],
        ),
    ]
