# Generated by Django 5.0.6 on 2025-01-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='income',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='Cash', max_length=20),
        ),
    ]
