# Generated by Django 5.0.6 on 2025-01-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount_from_customer', models.FloatField(default=0)),
                ('service_fee', models.FloatField(default=0)),
                ('total_amount_before_discount', models.FloatField(default=0)),
                ('total_tax', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('payment_status1', models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID'), ('PARTIALLY', 'PARTIALLY')], default='UNPAID', max_length=20)),
                ('payment_status', models.BooleanField(default=False)),
                ('discount', models.FloatField(default=0)),
                ('bill_discount', models.FloatField(default=0)),
                ('save_status', models.BooleanField(default=False)),
                ('paid_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_from_customer', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('service_fee', models.FloatField(default=0)),
                ('total_price', models.FloatField()),
                ('total_tax', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='service.services')),
            ],
        ),
    ]
