# Generated by Django 5.0.6 on 2025-01-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='balance_amount',
            field=models.FloatField(default=0),
        ),
    ]
