# Generated by Django 5.0.6 on 2025-01-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('eid', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('service_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_order_client', to='service.orderitem')),
            ],
        ),
    ]
