# Generated by Django 5.0.6 on 2025-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_order_delivery_status_orderitem_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extra_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='govt_fine',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
