# Generated by Django 5.0.6 on 2025-06-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_orderitem_extra_amount_orderitem_govt_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_extra',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_fine',
            field=models.FloatField(default=0),
        ),
    ]
