# Generated by Django 5.0.6 on 2025-01-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id_number',
        ),
    ]
