# Generated by Django 5.0.6 on 2025-01-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('account', 'account'), ('admin', 'admin')], default='user', max_length=20),
        ),
    ]
